### ISSUE TITLE
Position 설정 값은 같은데 왜 컴포넌트 위치가 다르게 표시될까?

### ISSUE THREAD

**Issue by saseungg** [saseungg/why#8]
> profile 카드를 만들던 중 position 값을 똑같이 줬음에도 컴포넌트 위치가 다르게 표현되어 원인을 파악하고자 했다.

## 문제 화면 및 코드
두개의 컴포넌트의 new 박스 위치가 다르다. css 값은 동일한데 뭐가 문제일까? 일단 해당 화면에 대한 코드이다.
<img src="https://github.com/saseungg/why/assets/115215178/75163542-8456-4570-80d9-e997c031bded" width="300px" height="500px" />

```js
// Avatar 컴포넌트
const Avatar = ({ image, isNew }) => {
  return (
    <div className='avatar'>
      <img className="image" src={image} alt="avatar" />
      {isNew && <span className="new">NEW</span>}
    </div>
  );
};
```

```js
// Profile 컴포넌트
const Profile = ({ image, name, title, isNew }) => {
  return (
    <div className="profile">
      <Avatar image={image} isNew={isNew}/>
      <h1>{name}</h1>
      <span>{title}</span>
    </div>
  );
};

```
```js
// App에서 Profile과 Avatar 컴포넌트를 선언했음
    <>
      <Profile image={image} isNew={isNew} />
      <Avatar image={image} isNew={isNew} />
    </>
```

```css
.avatar {
  position: relative;
}

.image {
  width: 200px;
  height: 200px;
  border-radius: 100%;
}

.new {
  width: 50px;
  border-radius: 10px;

  padding: 5px;
  position: absolute;
  top: 20px;
  left: 80px;

  text-align: center;
  background-color: rgb(160, 250, 244);
}
```

왜 둘의 new 박스의 위치가 다를까?
position은 동일한 위치에 있을 것인데 다르게 나오는지 이해가 안갔다.

## 원인
원인은 avatar의 사이즈값이다. 
avatar 사이즈값을 지정하지 않으니 Profile 컴포넌트 내에서 avatar 컴포넌트를 선언함으로써 avatar의 사이즈값이 커졌다. 

<img src="https://github.com/saseungg/why/assets/115215178/39dd0042-9aec-4f8d-a1e0-96af26ce45d3" width="200px" height="200px" />

```css
.avatar {
  position: relative;
  width: 200px;
  height: 200px;
}

.image {
  width: 200px;
  height: 200px;
  border-radius: 100%;
}
```
이미지랑 동일한 사이즈값으로 변경하니 해결!

<img src="https://github.com/saseungg/why/assets/115215178/f6e812bd-777f-40d8-bea2-6ceaaf1da3f7" width="200px" height="200px" />

이미지를 가운데로 오게 하기 위해 avatar에 `maring: auto;`를 주고 top, left-> right로 설정값을 수정하면 아래와 같이 표시된다!
<img src="https://github.com/saseungg/why/assets/115215178/11d17bed-9bf6-45b4-8fc0-1c48564aa420" width="200px" height="200px" />

## 최종 코드
```css
.avatar {
  position: relative;
  width: 200px;
  height: 200px;
  margin: auto;
}

.image {
  width: 200px;
  height: 200px;
  border-radius: 100%;
}

.new {
  width: 50px;
  border-radius: 10px;

  padding: 5px;
  position: absolute;
  top: 25px;
  right: 5px;

  text-align: center;
  background-color: rgb(160, 250, 244);
}

```
